### ISSUE TITLE
Remove InstallationSteps.md from the website

### ISSUE THREAD

**Issue by rishuatgithub** [atmenterprise/atm#3]
Issue with the website. InstallationSteps.md file is visible. Need to remove it.

**Comment by chahmedejaz** [comment]
Hey @rishuatgithub - Hope you are doing good. I'd like to pick this issue. Can you please assign it to me? Thanks. :)

**Comment by rishuatgithub** [comment]
send me a pull request.

**Comment by chahmedejaz** [comment]
Sure, @rishuatgithub. Working on it and sending it soon. :)

**Comment by chahmedejaz** [comment]
@rishuatgithub - Please review the PR and let me know if it's not fixed for you. Thanks.
